# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-16 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20181114_1453'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinorder',
            options={'verbose_name': 'Product in Order', 'verbose_name_plural': 'Products in Order'},
        ),
    ]
